<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectDataSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'id' => 1,
                'name' => 'Project Title 1',
                'responsible' => 'Person Name 1',
                'client' => 'Customer Name 1',
                'budget' => 2500,
                'start_date' => '2017-06-01',
                'days' => 365,
                'end_date' => '2018-10-26',
                'complexity' => 'Level 1',
                'priority' => 'Medium',
                'status' => 'Completed',
                'invoiced' => 400,
            ],
            [
                'id' => 2,
                'name' => 'Project Title 2',
                'responsible' => 'Person Name 2',
                'client' => 'Customer Name 2',
                'budget' => 2500,
                'start_date' => '2017-07-10',
                'days' => 350,
                'end_date' => '2018-11-13',
                'complexity' => 'Level 2',
                'priority' => 'Medium',
                'status' => 'Completed',
                'invoiced' => 400,
            ],
            [
                'id' => 3,
                'name' => 'Project Title 3',
                'responsible' => 'Person Name 3',
                'client' => 'Customer Name 3',
                'budget' => 2000,
                'start_date' => '2017-10-10',
                'days' => 400,
                'end_date' => '2019-04-30',
                'complexity' => 'Level 3',
                'priority' => 'Low',
                'status' => 'InProgress',
                'invoiced' => 600,
            ],
            [
                'id' => 4,
                'name' => 'Project Title 4',
                'responsible' => 'Person Name 4',
                'client' => 'Customer Name 4',
                'budget' => 2500,
                'start_date' => '2018-01-01',
                'days' => 50,
                'end_date' => '2018-03-09',
                'complexity' => 'Level 1',
                'priority' => 'Low',
                'status' => 'InProgress',
                'invoiced' => 500,
            ],
            [
                'id' => 5,
                'name' => 'Project Title 5',
                'responsible' => 'Person Name 5',
                'client' => 'Customer Name 5',
                'budget' => 3000,
                'start_date' => '2018-01-05',
                'days' => 100,
                'end_date' => '2018-05-25',
                'complexity' => 'Level 2',
                'priority' => 'High',
                'status' => 'InProgress',
                'invoiced' => 500,
            ],
            [
                'id' => 6,
                'name' => 'Project Title 6',
                'responsible' => 'Person Name 6',
                'client' => 'Customer Name 6',
                'budget' => 1000,
                'start_date' => '2018-01-10',
                'days' => 120,
                'end_date' => '2018-06-27',
                'complexity' => 'Level 3',
                'priority' => 'High',
                'status' => 'InProgress',
                'invoiced' => 200,
            ],
            [
                'id' => 7,
                'name' => 'Project Title 7',
                'responsible' => 'Person Name 7',
                'client' => 'Customer Name 7',
                'budget' => 2200,
                'start_date' => '2018-07-24',
                'days' => 350,
                'end_date' => '2019-11-29',
                'complexity' => 'Level 1',
                'priority' => 'Medium',
                'status' => 'Open',
                'invoiced' => 400,
            ],
            [
                'id' => 8,
                'name' => 'Project Title 8',
                'responsible' => 'Person Name 8',
                'client' => 'Customer Name 8',
                'budget' => 2000,
                'start_date' => '2018-09-22',
                'days' => 300,
                'end_date' => '2019-11-20',
                'complexity' => 'Level 2',
                'priority' => 'Medium',
                'status' => 'Open',
                'invoiced' => 500,
            ],
            [
                'id' => 9,
                'name' => 'Project Title 9',
                'responsible' => 'Person Name 9',
                'client' => 'Customer Name 9',
                'budget' => 2500,
                'start_date' => '2018-11-21',
                'days' => 200,
                'end_date' => '2019-09-02',
                'complexity' => 'Level 3',
                'priority' => 'Low',
                'status' => 'Open',
                'invoiced' => 300,
            ],
            [
                'id' => 10,
                'name' => 'Project Title 10',
                'responsible' => 'Person Name 10',
                'client' => 'Customer Name 10',
                'budget' => 3000,
                'start_date' => '2019-01-20',
                'days' => 200,
                'end_date' => '2019-10-24',
                'complexity' => 'Level 1',
                'priority' => 'Low',
                'status' => 'Open',
                'invoiced' => 0,
            ],
            [
                'id' => 11,
                'name' => 'Project Title 11',
                'responsible' => 'Person Name 11',
                'client' => 'Customer Name 9',
                'budget' => 3000,
                'start_date' => '2019-03-21',
                'days' => 400,
                'end_date' => '2020-09-30',
                'complexity' => 'Level 2',
                'priority' => 'High',
                'status' => 'Open',
                'invoiced' => 0,
            ],
            [
                'id' => 12,
                'name' => 'Project Title 12',
                'responsible' => 'Person Name 12',
                'client' => 'Customer Name 8',
                'budget' => 1800,
                'start_date' => '2019-05-20',
                'days' => 200,
                'end_date' => '2020-02-21',
                'complexity' => 'Level 3',
                'priority' => 'High',
                'status' => 'Open',
                'invoiced' => 0,
            ],
        ];

        foreach ($projects as $project) {
            DB::table('projects')->updateOrInsert(['id' => $project['id']], $project);
        }
    }
}
