<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RiskDataSeeder extends Seeder
{
    // score = likelihood x impact
    // level: Low / Medium / High / Extreme
    public function run(): void
    {
        $risks = [
            [
                'id' => 1,
                'description' => 'Risk Description 1',
                'project' => 'Project Title 1',
                'owner' => 'Person Name 1',
                'likelihood' => 0.05,
                'impact' => 0.05,
                'identified_on' => '2017-04-01',
                'last_updated' => '2017-04-16',
                'category' => 'Amend',
                'status' => 'Requested',
                'score' => 0.0025,
                'level' => 'Low',
            ],
            [
                'id' => 2,
                'description' => 'Risk Description 2',
                'project' => 'Project Title 1',
                'owner' => 'Person Name 2',
                'likelihood' => 0.1,
                'impact' => 0.1,
                'identified_on' => '2017-05-09',
                'last_updated' => '2017-05-24',
                'category' => 'Risk',
                'status' => 'In Progress',
                'score' => 0.01,
                'level' => 'Low',
            ],
            [
                'id' => 3,
                'description' => 'Risk Description 3',
                'project' => 'Project Title 1',
                'owner' => 'Person Name 3',
                'likelihood' => 0.1,
                'impact' => 0.1,
                'identified_on' => '2017-05-10',
                'last_updated' => '2017-05-25',
                'category' => 'Risk',
                'status' => 'Complete',
                'score' => 0.01,
                'level' => 'Low',
            ],
            [
                'id' => 4,
                'description' => 'Risk Description 4',
                'project' => 'Project Title 4',
                'owner' => 'Person Name 4',
                'likelihood' => 0.1,
                'impact' => 0.1,
                'identified_on' => '2017-05-11',
                'last_updated' => '2017-05-26',
                'category' => 'Question',
                'status' => 'In Progress',
                'score' => 0.01,
                'level' => 'Low',
            ],
            [
                'id' => 5,
                'description' => 'Risk Description 5',
                'project' => 'Project Title 5',
                'owner' => 'Person Name 5',
                'likelihood' => 0.15,
                'impact' => 0.15,
                'identified_on' => '2017-05-12',
                'last_updated' => '2017-05-27',
                'category' => 'Other',
                'status' => 'Requested',
                'score' => 0.0225,
                'level' => 'Low',
            ],
            [
                'id' => 6,
                'description' => 'Risk Description 6',
                'project' => 'Project Title 8',
                'owner' => 'Person Name 6',
                'likelihood' => 0.05,
                'impact' => 0.05,
                'identified_on' => '2017-05-13',
                'last_updated' => '2017-05-28',
                'category' => 'Risk',
                'status' => 'In Progress',
                'score' => 0.0025,
                'level' => 'Low',
            ],
            [
                'id' => 7,
                'description' => 'Risk Description 7',
                'project' => 'Project Title 9',
                'owner' => 'Person Name 7',
                'likelihood' => 0.6,
                'impact' => 0.5,
                'identified_on' => '2017-05-14',
                'last_updated' => '2017-05-29',
                'category' => 'Risk',
                'status' => 'Approved',
                'score' => 0.3,
                'level' => 'Medium',
            ],
            [
                'id' => 8,
                'description' => 'Risk Description 8',
                'project' => 'Project Title 8',
                'owner' => 'Person Name 8',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-15',
                'last_updated' => '2017-05-30',
                'category' => 'Issue',
                'status' => 'In Progress',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 9,
                'description' => 'Risk Description 9',
                'project' => 'Project Title 9',
                'owner' => 'Person Name 9',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-16',
                'last_updated' => '2017-05-31',
                'category' => 'Other',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 10,
                'description' => 'Risk Description 10',
                'project' => 'Project Title 10',
                'owner' => 'Person Name 10',
                'likelihood' => 0.45,
                'impact' => 0.45,
                'identified_on' => '2017-05-17',
                'last_updated' => '2017-06-01',
                'category' => 'Issue',
                'status' => 'In Progress',
                'score' => 0.2025,
                'level' => 'Low',
            ],
            [
                'id' => 11,
                'description' => 'Risk Description 11',
                'project' => 'Project Title 11',
                'owner' => 'Person Name 11',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-18',
                'last_updated' => '2017-06-02',
                'category' => 'Issue',
                'status' => 'Complete',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 12,
                'description' => 'Risk Description 12',
                'project' => 'Project Title 12',
                'owner' => 'Person Name 12',
                'likelihood' => 0.75,
                'impact' => 0.75,
                'identified_on' => '2017-05-19',
                'last_updated' => '2017-06-03',
                'category' => 'Question',
                'status' => 'In Progress',
                'score' => 0.5625,
                'level' => 'High',
            ],
            [
                'id' => 13,
                'description' => 'Risk Description 1',
                'project' => 'Project Title 4',
                'owner' => 'Person Name 13',
                'likelihood' => 0.05,
                'impact' => 0.05,
                'identified_on' => '2017-04-01',
                'last_updated' => '2017-04-16',
                'category' => 'Amend',
                'status' => 'Requested',
                'score' => 0.0025,
                'level' => 'Low',
            ],
            [
                'id' => 14,
                'description' => 'Risk Description 2',
                'project' => 'Project Title 2',
                'owner' => 'Person Name 14',
                'likelihood' => 0.6,
                'impact' => 0.5,
                'identified_on' => '2017-05-09',
                'last_updated' => '2017-05-24',
                'category' => 'Risk',
                'status' => 'In Progress',
                'score' => 0.3,
                'level' => 'Medium',
            ],
            [
                'id' => 15,
                'description' => 'Risk Description 3',
                'project' => 'Project Title 3',
                'owner' => 'Person Name 1',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-10',
                'last_updated' => '2017-05-25',
                'category' => 'Risk',
                'status' => 'Complete',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 16,
                'description' => 'Risk Description 4',
                'project' => 'Project Title 4',
                'owner' => 'Person Name 2',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-11',
                'last_updated' => '2017-05-26',
                'category' => 'Question',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 17,
                'description' => 'Risk Description 5',
                'project' => 'Project Title 4',
                'owner' => 'Person Name 3',
                'likelihood' => 0.05,
                'impact' => 0.05,
                'identified_on' => '2017-05-12',
                'last_updated' => '2017-05-27',
                'category' => 'Other',
                'status' => 'Requested',
                'score' => 0.0025,
                'level' => 'Low',
            ],
            [
                'id' => 18,
                'description' => 'Risk Description 6',
                'project' => 'Project Title 4',
                'owner' => 'Person Name 4',
                'likelihood' => 0.6,
                'impact' => 0.5,
                'identified_on' => '2017-05-13',
                'last_updated' => '2017-05-28',
                'category' => 'Risk',
                'status' => 'In Progress',
                'score' => 0.3,
                'level' => 'Medium',
            ],
            [
                'id' => 19,
                'description' => 'Risk Description 7',
                'project' => 'Project Title 8',
                'owner' => 'Person Name 5',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-14',
                'last_updated' => '2017-05-29',
                'category' => 'Risk',
                'status' => 'Approved',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 20,
                'description' => 'Risk Description 8',
                'project' => 'Project Title 8',
                'owner' => 'Person Name 6',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-15',
                'last_updated' => '2017-05-30',
                'category' => 'Issue',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 21,
                'description' => 'Risk Description 9',
                'project' => 'Project Title 9',
                'owner' => 'Person Name 7',
                'likelihood' => 0.05,
                'impact' => 0.05,
                'identified_on' => '2017-05-16',
                'last_updated' => '2017-05-31',
                'category' => 'Other',
                'status' => 'In Progress',
                'score' => 0.0025,
                'level' => 'Low',
            ],
            [
                'id' => 22,
                'description' => 'Risk Description 10',
                'project' => 'Project Title 11',
                'owner' => 'Person Name 8',
                'likelihood' => 0.6,
                'impact' => 0.5,
                'identified_on' => '2017-05-17',
                'last_updated' => '2017-06-01',
                'category' => 'Issue',
                'status' => 'In Progress',
                'score' => 0.3,
                'level' => 'Medium',
            ],
            [
                'id' => 23,
                'description' => 'Risk Description 11',
                'project' => 'Project Title 11',
                'owner' => 'Person Name 9',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-18',
                'last_updated' => '2017-06-02',
                'category' => 'Issue',
                'status' => 'Complete',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 24,
                'description' => 'Risk Description 12',
                'project' => 'Project Title 12',
                'owner' => 'Person Name 10',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-19',
                'last_updated' => '2017-06-03',
                'category' => 'Question',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 25,
                'description' => 'Risk Description 3',
                'project' => 'Project Title 1',
                'owner' => 'Person Name 11',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-10',
                'last_updated' => '2017-05-25',
                'category' => 'Risk',
                'status' => 'Complete',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 26,
                'description' => 'Risk Description 4',
                'project' => 'Project Title 2',
                'owner' => 'Person Name 12',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-11',
                'last_updated' => '2017-05-26',
                'category' => 'Question',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 27,
                'description' => 'Risk Description 5',
                'project' => 'Project Title 3',
                'owner' => 'Person Name 13',
                'likelihood' => 0.05,
                'impact' => 0.05,
                'identified_on' => '2017-05-12',
                'last_updated' => '2017-05-27',
                'category' => 'Other',
                'status' => 'Requested',
                'score' => 0.0025,
                'level' => 'Low',
            ],
            [
                'id' => 28,
                'description' => 'Risk Description 6',
                'project' => 'Project Title 6',
                'owner' => 'Person Name 14',
                'likelihood' => 0.6,
                'impact' => 0.5,
                'identified_on' => '2017-05-13',
                'last_updated' => '2017-05-28',
                'category' => 'Risk',
                'status' => 'In Progress',
                'score' => 0.3,
                'level' => 'Medium',
            ],
            [
                'id' => 29,
                'description' => 'Risk Description 7',
                'project' => 'Project Title 5',
                'owner' => 'Person Name 15',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-14',
                'last_updated' => '2017-05-29',
                'category' => 'Risk',
                'status' => 'Approved',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 30,
                'description' => 'Risk Description 8',
                'project' => 'Project Title 4',
                'owner' => 'Person Name 15',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-15',
                'last_updated' => '2017-05-30',
                'category' => 'Issue',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 31,
                'description' => 'Risk Description 9',
                'project' => 'Project Title 4',
                'owner' => 'Person Name 3',
                'likelihood' => 0.05,
                'impact' => 0.05,
                'identified_on' => '2017-05-16',
                'last_updated' => '2017-05-31',
                'category' => 'Other',
                'status' => 'In Progress',
                'score' => 0.0025,
                'level' => 'Low',
            ],
            [
                'id' => 32,
                'description' => 'Risk Description 10',
                'project' => 'Project Title 8',
                'owner' => 'Person Name 4',
                'likelihood' => 0.6,
                'impact' => 0.5,
                'identified_on' => '2017-05-17',
                'last_updated' => '2017-06-01',
                'category' => 'Issue',
                'status' => 'In Progress',
                'score' => 0.3,
                'level' => 'Medium',
            ],
            [
                'id' => 33,
                'description' => 'Risk Description 11',
                'project' => 'Project Title 9',
                'owner' => 'Person Name 5',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-18',
                'last_updated' => '2017-06-02',
                'category' => 'Issue',
                'status' => 'Complete',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 34,
                'description' => 'Risk Description 12',
                'project' => 'Project Title 8',
                'owner' => 'Person Name 6',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-19',
                'last_updated' => '2017-06-03',
                'category' => 'Question',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
            [
                'id' => 35,
                'description' => 'Risk Description 13',
                'project' => 'Project Title 8',
                'owner' => 'Person Name 7',
                'likelihood' => 0.8,
                'impact' => 0.8,
                'identified_on' => '2017-05-18',
                'last_updated' => '2017-06-02',
                'category' => 'Issue',
                'status' => 'Complete',
                'score' => 0.64,
                'level' => 'High',
            ],
            [
                'id' => 36,
                'description' => 'Risk Description 14',
                'project' => 'Project Title 12',
                'owner' => 'Person Name 8',
                'likelihood' => 0.95,
                'impact' => 0.95,
                'identified_on' => '2017-05-19',
                'last_updated' => '2017-06-03',
                'category' => 'Question',
                'status' => 'In Progress',
                'score' => 0.9025,
                'level' => 'Extreme',
            ],
        ];

        foreach ($risks as $risk) {
            DB::table('risks')->updateOrInsert(['id' => $risk['id']], $risk);
        }
    }
}
